flags: {}
extra-package-dbs: []
packages:
- .
extra-deps: [Stack-0.4.0 
            , deepseq-1.4.4.0 
            , stm-2.5.0.0
            , binary-0.8.8.0
            , bytestring-0.10.10.0
            , containers-0.6.2.1
            , directory-1.3.6.1
            , pretty-1.1.3.6
            , process-1.6.9.0
            , time-1.9.3
            , unix-2.7.2.2
            , text-1.2.4.0
            ]
resolver: lts-14.20
#resolver: lts-12.6
