/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package HaskTiger-0.1.0.0 */
#ifndef VERSION_HaskTiger
#define VERSION_HaskTiger "0.1.0.0"
#endif /* VERSION_HaskTiger */
#ifndef MIN_VERSION_HaskTiger
#define MIN_VERSION_HaskTiger(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_HaskTiger */

/* package base-4.11.1.0 */
#ifndef VERSION_base
#define VERSION_base "4.11.1.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  11 || \
  (major1) == 4 && (major2) == 11 && (minor) <= 1)
#endif /* MIN_VERSION_base */

/* package containers-0.5.11.0 */
#ifndef VERSION_containers
#define VERSION_containers "0.5.11.0"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 11)
#endif /* MIN_VERSION_containers */

/* package text-1.2.3.0 */
#ifndef VERSION_text
#define VERSION_text "1.2.3.0"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_text */

/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */

/* package parsec-3.1.13.0 */
#ifndef VERSION_parsec
#define VERSION_parsec "3.1.13.0"
#endif /* VERSION_parsec */
#ifndef MIN_VERSION_parsec
#define MIN_VERSION_parsec(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  1 || \
  (major1) == 3 && (major2) == 1 && (minor) <= 13)
#endif /* MIN_VERSION_parsec */

/* package pretty-1.1.3.6 */
#ifndef VERSION_pretty
#define VERSION_pretty "1.1.3.6"
#endif /* VERSION_pretty */
#ifndef MIN_VERSION_pretty
#define MIN_VERSION_pretty(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 3)
#endif /* MIN_VERSION_pretty */

/* package cond-0.4.1.1 */
#ifndef VERSION_cond
#define VERSION_cond "0.4.1.1"
#endif /* VERSION_cond */
#ifndef MIN_VERSION_cond
#define MIN_VERSION_cond(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 1)
#endif /* MIN_VERSION_cond */

/* package transformers-0.5.5.0 */
#ifndef VERSION_transformers
#define VERSION_transformers "0.5.5.0"
#endif /* VERSION_transformers */
#ifndef MIN_VERSION_transformers
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 5)
#endif /* MIN_VERSION_transformers */

/* package syb-0.7 */
#ifndef VERSION_syb
#define VERSION_syb "0.7"
#endif /* VERSION_syb */
#ifndef MIN_VERSION_syb
#define MIN_VERSION_syb(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 0)
#endif /* MIN_VERSION_syb */

/* package template-haskell-2.13.0.0 */
#ifndef VERSION_template_haskell
#define VERSION_template_haskell "2.13.0.0"
#endif /* VERSION_template_haskell */
#ifndef MIN_VERSION_template_haskell
#define MIN_VERSION_template_haskell(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  13 || \
  (major1) == 2 && (major2) == 13 && (minor) <= 0)
#endif /* MIN_VERSION_template_haskell */

/* tool gcc-7 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "7"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  7 || \
  (major1) == 7 && (major2) <  0 || \
  (major1) == 7 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.4.3 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.4.3"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  4 || \
  (major1) == 8 && (major2) == 4 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.4.3 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.4.3"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  4 || \
  (major1) == 8 && (major2) == 4 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.20.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.20.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  20 || \
  (major1) == 2 && (major2) == 20 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.67 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.67"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.3 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.3"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool runghc-8.4.3 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.4.3"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  4 || \
  (major1) == 8 && (major2) == 4 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.30 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.30"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  30 || \
  (major1) == 2 && (major2) == 30 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "HaskTiger-0.1.0.0-ICRikAExwdr6IYW5QWtTsY"
#endif /* CURRENT_PACKAGE_KEY */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "HaskTiger-0.1.0.0-ICRikAExwdr6IYW5QWtTsY"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package HaskTiger-0.1.0.0 */
#ifndef VERSION_HaskTiger
#define VERSION_HaskTiger "0.1.0.0"
#endif /* VERSION_HaskTiger */
#ifndef MIN_VERSION_HaskTiger
#define MIN_VERSION_HaskTiger(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_HaskTiger */

/* package base-4.11.1.0 */
#ifndef VERSION_base
#define VERSION_base "4.11.1.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  11 || \
  (major1) == 4 && (major2) == 11 && (minor) <= 1)
#endif /* MIN_VERSION_base */

/* package containers-0.5.11.0 */
#ifndef VERSION_containers
#define VERSION_containers "0.5.11.0"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 11)
#endif /* MIN_VERSION_containers */

/* package text-1.2.3.0 */
#ifndef VERSION_text
#define VERSION_text "1.2.3.0"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_text */

/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */

/* package parsec-3.1.13.0 */
#ifndef VERSION_parsec
#define VERSION_parsec "3.1.13.0"
#endif /* VERSION_parsec */
#ifndef MIN_VERSION_parsec
#define MIN_VERSION_parsec(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  1 || \
  (major1) == 3 && (major2) == 1 && (minor) <= 13)
#endif /* MIN_VERSION_parsec */

/* package pretty-1.1.3.6 */
#ifndef VERSION_pretty
#define VERSION_pretty "1.1.3.6"
#endif /* VERSION_pretty */
#ifndef MIN_VERSION_pretty
#define MIN_VERSION_pretty(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 3)
#endif /* MIN_VERSION_pretty */

/* package cond-0.4.1.1 */
#ifndef VERSION_cond
#define VERSION_cond "0.4.1.1"
#endif /* VERSION_cond */
#ifndef MIN_VERSION_cond
#define MIN_VERSION_cond(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 1)
#endif /* MIN_VERSION_cond */

/* package transformers-0.5.5.0 */
#ifndef VERSION_transformers
#define VERSION_transformers "0.5.5.0"
#endif /* VERSION_transformers */
#ifndef MIN_VERSION_transformers
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 5)
#endif /* MIN_VERSION_transformers */

/* package HaskTiger-0.1.0.0 */
#ifndef VERSION_HaskTiger
#define VERSION_HaskTiger "0.1.0.0"
#endif /* VERSION_HaskTiger */
#ifndef MIN_VERSION_HaskTiger
#define MIN_VERSION_HaskTiger(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_HaskTiger */

/* tool gcc-7 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "7"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  7 || \
  (major1) == 7 && (major2) <  0 || \
  (major1) == 7 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.4.3 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.4.3"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  4 || \
  (major1) == 8 && (major2) == 4 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.4.3 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.4.3"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  4 || \
  (major1) == 8 && (major2) == 4 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.20.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.20.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  20 || \
  (major1) == 2 && (major2) == 20 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.67 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.67"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.3 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.3"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool runghc-8.4.3 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.4.3"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  4 || \
  (major1) == 8 && (major2) == 4 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.30 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.30"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  30 || \
  (major1) == 2 && (major2) == 30 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "HaskTiger-0.1.0.0-14wQe76EC4nKtOOaZVSDUB-HaskTiger"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
